global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'scraparr'
    static_configs:
      - targets: ['host.docker.internal:7100']
  - job_name: 'tailscale'
    static_configs:
      - targets: ['100.100.100.100:80']